title: "PR-CYBR"
description: "Official PR-CYBR website for digital resilience and community protection."
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
show_downloads: false
